INSERT INTO user(name, gender, age, email)
    VALUES ("キラメキ太郎", "男性", 27, 'taro.kirameki@mail.com')
INSERT INTO user(name, gender, age, email)
    VALUES ("キラメキ次郎", "男性", 27, 'jiro.kirameki@mail.com')
INSERT INTO user(name, gender, age, email)
    VALUES ("キラメキ花子", "女性", 27, 'hanako.kirameki@mail.com')